In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression


In [2]:
data = pd.read_csv('house.csv')
data.head()

loyer  surface
0   1330       37
1   1400       32
2    904       26
3    955       30
4   2545       70

In [3]:
data['random123'] = np.random.randint(1, 4, data.shape[0])
data


loyer  surface  random123
0     1330       37          2
1     1400       32          1
2      904       26          1
3      955       30          2
4     2545       70          1
..     ...      ...        ...
540   1490       48          3
541   2020       58          2
542   2050       70          2
543   1220       42          3
544   1610       44          2

[545 rows x 3 columns]

In [4]:
x = data[['loyer','random123']]
y = data['surface']

# Standardization

In [9]:
from sklearn.preprocessing import StandardScaler 

In [10]:
scaler = StandardScaler()

StandardScaler() is a preprocessing module used to standardize (or scale) data

In [11]:
scaler.fit(x)

StandardScaler()

StandardScaler.transform(x) transfors the unscaled inputs using the information contained in the scaler object (feature_wise)

In [12]:
x_scaled = scaler.transform(x)

In [13]:
x_scaled

array([[-0.444452  ,  0.0136613 ],
       [-0.41262432, -1.22723973],
       [-0.63814613, -1.22723973],
       ...,
       [-0.11708163,  0.0136613 ],
       [-0.49446691,  1.25456232],
       [-0.3171413 ,  0.0136613 ]])

# Regression with scaled features

In [14]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [15]:
reg.coef_

array([44.12935252,  0.91083935])

In [17]:
reg.intercept_

63.236697247706424

# Creating a summary table

In [21]:
reg_summary = pd.DataFrame([['Bias'],['loyer'],['random123']], columns=['Features'])
reg_summary['weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [22]:
reg_summary

Features    weights
0       Bias  63.236697
1      loyer  44.129353
2  random123   0.910839

it si great to standardize so that we can see witch feature has the biggest effect by comparing the coefficients but we can not campare the coeficients if data is not standardized

the bigger the weight the bigger the impact

the intercept is called the bias in ml

we can see that random123 barely contributes to our output, if at all

# Making predictions with the standardized coefficients (weights)

In [24]:
new_data = pd.DataFrame(data=[[1350,2],[1360,1]], columns=['loyer', 'random123'])
new_data

loyer  random123
0   1350          2
1   1360          1

In [25]:
reg.predict(new_data)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([59639.68427408, 60080.06695991])

In [26]:
#what the hell is that , it is becouse we fit standardized data to the model but now we are fitting data that is not standardized 

In [27]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled


array([[-0.43535837,  0.0136613 ],
       [-0.43081156, -1.22723973]])

In [28]:
reg.predict(new_data_scaled)

array([44.03705732, 43.10744366])

# what if we removed the random123 variable?

In [30]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix, y)

LinearRegression()

In [31]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1, 1))

array([44.02409476, 44.224748  ])

the result is prety the same with the result without removing random123 THAT IS WHY THE USERS OF SKLEARN DON'T CARE ABOUT P_VALUES BECAUSE WHEN APPLY SCALING IT DOES NOT MUTTER IF WE KEEP OR LEAVE INSIGNIFICANT VALUES